(GH-478) Suppress the `CS0618` warning to avoid breaking the build
This attribute causes the following warning which, if not suppressed, is treated as a failure when building:
C:\projects\stronggrid\Source\StrongGrid\Json\StrongGridJsonSerializerContext.cs(115,27): error CS0618: 'NewRelicSettings' is obsolete: 'Twilio SendGrid no longer supports SendGrid for New Relic and the related integration features as of August 30, 2022.'